### ISSUE TITLE
Vlos nomenclature

### ISSUE THREAD

**Issue by andycasey** [jobovy/galpy#233]
Hi Jo,

I've opened this issue to resolve a discussion regarding `Vlos` when initialising a `galpy.orbit.Orbit`. It's a simple question, but I'd like to be sure. It's arisen because the terms `V_los`, `V_rad`, `V_hel` are frequently (and incorrectly) used interchangeably by some people, myself included.

When you refer to `Vlos` as the line-of-sight velocity [in the documentation](https://github.com/jobovy/galpy/blob/master/doc/source/orbit.rst), do you mean the velocity observed from the telescope on some night of observation (what I usually call the line-of-sight velocity), or do you mean the observed velocity **after** accounting for the motion of the Earth (e.g., the heliocentric velocity)?

I would assume `Vlos` is actually the latter because `galpy` has no knowledge of where the object was observed from or when. Otherwise the `Vlos` would vary by up to +/- 30 km/s and the inferred orbit would be slightly different depending on which nights' observations were used.

Is my assumption correct or have I missed something here?

Thanks,
Andy

**Comment by jobovy** [comment]
Hi Andy,

The ``Vlos`` input is the heliocentric line-of-sight velocity. I dislike using 'radial velocity' or ``Vrad`` for this, as I always confuse that with the Galactocentric radial velocity, but you're right that ``Vhel`` would probably be a better name. I've clarified the documentation.

Thanks,

Jo

**Comment by andycasey** [comment]
Hi Jo,

I thought that might be the reason why you had named it `Vlos`. Thanks for clarifying that.

Cheers
