### ISSUE TITLE
General potential of disks

### ISSUE THREAD

**Issue by iogiul** [jobovy/galpy#234]
Hi, i am working on the estimate of potential for a disk with a scale height varying with the Radius (as in the case of flaring disks). 
I wonder if you can be interested to include this function in galpy, once I have a robust and tested code to evaluate this kind of potential.
In this context, for a comparison, can I ask how much you are confident on the evaluation of the potential of the double exponential disk in galpy?

**Comment by jobovy** [comment]
Hi,

Yes, this would be interesting to add. Once you have the code working, I would recommend forking galpy and adding this new potential in the fork. An example of a pull request adding a potential is #232, which you can look at for some of the necessary steps (not all of these are relevant, but testing and documentation is important).

Evaluating a double exponential disk potential is difficult. Orbital properties are typically accurate to about 0.1% (see the nose/test_orbit.py test code), the potential, forces, and derivatives are accurate to about 1% (see tests in nose/test_potential.py). I haven't tested the accuracy terribly much and I think that for most cases the potential is more accurate than these worst cases.

Thanks,

Jo

**Comment by jobovy** [comment]
Closing this, because it's not a real issue and nothing is happening on this front.

**Comment by jobovy** [comment]
For reference: general disk potentials are now supported through the [DiskSCFPotential](http://galpy.readthedocs.io/en/latest/reference/potentialdiskscf.html) class, which should be straightforward to setup for a flaring disk using the examples given [in this section of the documentation](http://galpy.readthedocs.io/en/latest/potential.html#new-in-v1-2-updated-in-v1-3-general-density-potential-pairs-with-basis-function-expansions).

**Comment by iogiul** [comment]
Thank you for the information!

I have my code to calculate it with a classical double integration, but this look very interesting also in term of computational time!

Giuliano

Il giorno 02 gen 2017, alle ore 17:42, Jo Bovy <notifications@github.com<mailto:notifications@github.com>> ha scritto:


For reference: general disk potentials are now supported through the DiskSCFPotential<http://galpy.readthedocs.io/en/latest/reference/potentialdiskscf.html> class, which should be straightforward to setup for a flaring disk using the examples given in this section of the documentation<http://galpy.readthedocs.io/en/latest/potential.html#new-in-v1-2-updated-in-v1-3-general-density-potential-pairs-with-basis-function-expansions>.

**Comment by jobovy** [comment]
Yes, it should be quite a bit faster than using direct integration, but it would be great to check the accuracy against the direct computation.
