### ISSUE TITLE
calling Orbit and LookupError

### ISSUE THREAD

**Issue by smoh** [jobovy/galpy#256]
Hi Jo,

I had a question about the behavior of `Orbit.__call__`, which is called internally
when I access e.g., Orbit.R(t). It seems that it does not raise any error when I don't integrate and try to access t>0 and simply outputs t=0 values all the time.
```
from galpy.orbit import Orbit
o = Orbit(vxvv=[5.,-1.,0.8, 3, -0.1, 0])
# no integration of the orbit
print o.R(0), o.R(30)  # 5, 5
# No error raised
```
I could not parse all the codes involved, but was wondering if the LookupError (https://github.com/jobovy/galpy/blob/master/galpy/orbit_src/OrbitTop.py#L1144) is not being properly raised in this case?

**Comment by jobovy** [comment]
Hi Semyeong,

You're right, this behavior is undesired. The reason this failed to raise an Error is that a 'fake' interpolation is setup before one integrates the orbit and the evaluation of this fake interpolation didn't check that the time given == 0. This is now fixed in master.

Thanks,

Jo
