### ISSUE TITLE
Bad files in tarball on pypi

### ISSUE THREAD

**Issue by mwcraig** [jobovy/galpy#259]
The tarball has a few files that look like they are left over from fixing a git conflict:

```
integratePlanarOrbit_BACKUP_97677.py
integratePlanarOrbit_BASE_97677.py
integratePlanarOrbit_LOCAL_97677.py
integratePlanarOrbit_REMOTE_97677.py
```
They are all in `galpy/orbit_src`.

Unfortunately, there is no way to replace a tarball on pypi, so the options would be to issue a "post" release (e.g. `1.1.post1`, meaning no changes to any of the functional parts of the package) or a bugfix release. FWIW, when I last ran into this myself a couple months ago I just made a new bugfix release.

Noticed then when the galpy build of the conda package failed.

**Comment by jobovy** [comment]
I've uploaded a "post" release to PyPI. Please let me know if there are any issues with that.
