### ISSUE TITLE
Solution to #256 requires recent scipy version

### ISSUE THREAD

**Issue by fardal** [jobovy/galpy#261]
The solution to #256 involved a flag `ext=2` to a scipy interpolation routine.  This flag is introduced in scipy version 1.15.  I'm on current stable debian version 8.2 jessie, and apparently scipy 1.14 is standard on this version.  Not easy for me to update on this shared machine either.

My workaround is to insert this in `OrbitTop.py`:

    from scipy import __version__ as scipy_v
    if (int(scipy_v.split('.')[0]) > 0) or (int(scipy_v.split('.')[1]) >= 15):
        KWINTERP = {'ext':2}  #for scipy version >=1.15.0                             
    else:
        KWINTERP = {}  #for scipy version <1.15.0                                     

and then replace `ext=2` with `KWINTERP`.  Not sure this is a great solution but at least it runs now.

At least, a recommendation for specific scipy version in the installation docs would be useful.

**Comment by jobovy** [comment]
I've fixed this in the master branch along the lines that you suggested. You'd have to merge this into dynamfric if you want to use it there.
