### ISSUE TITLE
RazorThinExponentialDiskPotential does not accept arrays as input

### ISSUE THREAD

**Issue by NegriAndrea** [jobovy/galpy#265]
Trying to fed to RazorThinExponentialDiskPotential two numpy arrays results in an error, while it does't occur with MiyamotoNagaiPotential.

Here a basic example. The resulting error is _ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()_

`import numpy as np
from galpy.potential import RazorThinExponentialDiskPotential, MiyamotoNagaiPotential

R = np.logspace(0., 2., 10)
z=R

(RR,zz)=np.meshgrid(R,z)
# with RazorThinExponentialDiskPotential it does not work

potfunc=RazorThinExponentialDiskPotential()
# with Miyamoto Nagai it works
# potfunc=MiyamotoNagaiPotential()

pot=potfunc(RR,zz)
`

**Comment by jobovy** [comment]
Hi,

Array input for potentials is not generally supported currently, but I'll leave this issue open and plan to fix it soon. For now I would just use the workaround:
```
potfunc=numpy.array([RazorThinExponentialDiskPotential(r,z) for r,z in zip(RR,zz)])
```

The reason that this isn't supported for RazorThinExponentialDiskPotential (or DoubleExponentialDiskPotential) is that there isn't anything gained in terms of speed-up for arrays; each ``(R,z)`` needs to be handled separately for these potentials. For the potentials with simple analytical forms (like MiyamotoNagaiPotential) numpy functions are used such that array input works and is more efficient.

**Comment by NegriAndrea** [comment]
Many thanks for your help.


Cheers,
Andrea Negri
