### ISSUE TITLE
[feature-request] Aligning to target galaxy coordinate system

### ISSUE THREAD

**Issue by pkaf** [jobovy/galpy#268]
A handle on rotating and translating from heliocentric or galactic or galactocentric coordinates to target galaxy centric coordinate system would be a handy tool in applying galpy to distant system with known position and inclination angles.

**Comment by jobovy** [comment]
Could you elaborate on what you mean? Do you want to take the output from an orbit integration and project it as seen for a distance system?

**Comment by pkaf** [comment]
I found out that there is some confusion in the literature on coordinate conversion between heliocentric to M31 centric system ( or for that matter any distant galaxy with some p.a. and inclination) and viceversa, e.g. McConnachie et al. 2006 vs Metz et al. 2007 etc. I was wondering if such transformation can be incorporated in galpy coordinates. This has to do less with dynamics itself but more with again utils. Yes, I was thinking of something like projecting the output from an orbit integration for a distance system back into helio/galactic system.

**Comment by jobovy** [comment]
Okay, I think that something like this could be interesting. I don't have any time or reason to work on this now though, so I will leave this open to see whether anybody wants to try implementing this (perhaps you!).

**Comment by pkaf** [comment]
I may be able to contribute as I have to do it anyway for my ongoing project. Let's keep it open for the floor and see if any one else wants to jump in too. As I said the main purpose of this would be to convert heliocentric observation into distant galaxy (LMC, M31, elliptical galaxies etc)  centric frame to facilitate its dynamical modelling.
