### ISSUE TITLE
Missing 3/4pi factor in the density for Plummer force softening?

### ISSUE THREAD

**Issue by DouglasBoubert** [jobovy/galpy#269]
I'm interested in using the MovingObjectPotential, but looking through the definition of the Plummer softening in ForceSoftening.py there seems to be a missing factor of 3/4pi in the density. Have I missed a normalisation that happens elsewhere?

(I'm thinking about adding some more softenings, so it would be good to know exactly what is happening!)

**Comment by jobovy** [comment]
Yes, that's correct, thanks! It should be fixed now in ``master``. I guess I should really just re-use the functions in PlummerPotential.py...

Would be great if you want to add other softenings! I haven't used this very much, so there might be better ways to arrange the softening. There currently also isn't any way to use the C integration routines with MovingObjectPotential...
