### ISSUE TITLE
(pmll x cos(b),pmbb)

### ISSUE THREAD

**Issue by erwin0825** [jobovy/galpy#291]
In `galpy.util.bovy_coords.pmrapmdec_to_pmllpmbb`, the output is specified as `(pmll x cos(b),pmbb)`. Why is it not `(pmll, pmbb)` instead?

**Comment by jobovy** [comment]
pmll x cos(b) is the actual angular velocity, while pmll = d l / d t is just the coordinate velocity. pmll x cos (b) is typically what you want, to compute physical velocities (see [this note](https://github.com/jobovy/stellarkinematics/blob/master/stellarkinematics.pdf)). Catalogs like Gaia will give you pmra x cos(dec) for the same reason, and pmra x cos(dec) is therefore the input to pmrapmdec_to_pmllpmbb (so you typically do _not_ have to multiply cos(dec) in yourself, catalogs typically include this).
