### ISSUE TITLE
Confused about helio positions with physical units

### ISSUE THREAD

**Issue by fardal** [jobovy/galpy#294]
When I initialize an orbit with physical units, I'm getting Orbit.x returned in kpc, but Orbit.helioX returned in system units.  Is this the intended behavior?  (I've mostly initialized Orbit in system units but I'm trying to switch.)

    import astropy.units as u
    from galpy.orbit import Orbit
    kms = 1. * u.km / u.s
    kpc = u.kpc
    orb = Orbit(vxvv=[16.*kpc, 0.*kms, 0.*kms, 0.*kpc, 0.*kms, 0.*u.rad])
    print orb.x()
    print orb.helioX()

    >>> print orb.x()
    16.0
    >>> print orb.helioX()
    [-0.99998535]

(I see there's also an inconsistency in scalar vs vector, but I think you created an issue for this already.)

**Comment by jobovy** [comment]
Hi Mark,

As far as I can tell, this appears to be a long-standing issue where ``helioX()`` never actually returned the result in physical units, but in internal units (even though ``U`` did return results in km/s). When I added the unit support, I assumed that ``helioX`` and similar functions were already in physical units.

I'll have to look at this a little more closely, but will try to fix this soon.
