### ISSUE TITLE
Is Orbit.L returning L or -L?

### ISSUE THREAD

**Issue by fardal** [jobovy/galpy#295]
I just tried using Orbit.L and was surprised by the direction of rotation it implies.  Officially the angular momentum is regarded as a pseudovector and gains a minus sign under reflection symmetry compared to a regular vector.  If you're working in a left-handed coordinate system, such as the galactocentric system used within bovy_coords, shouldn't there be a minus sign applied to the result from the usual formula?  I get easily confused by this stuff so maybe not.

I'm not suggesting any change to the code...but maybe a note in the docs that would make the meaning of the output clearer.

**Comment by jobovy** [comment]
Can you given a cide example of what you mean?

**Comment by fardal** [comment]
```
from galpy.orbit import Orbit
from galpy.util import bovy_coords
import astropy.units as u

dist = 0.0001  #keep it in solar neighborhood
ll, bb = 90., 0.  #direction doesn't really matter because distance so small
pmll = 0.
pmbb = 0.
vrad = 0.
X, Y, Z = bovy_coords.lbd_to_XYZ(ll, bb, dist, degree=True)
vX, vY, vZ = bovy_coords.vrpmllpmbb_to_vxvyvz(
    vrad, pmll, pmbb, ll, bb, dist, 
    degree=True)
Rg, phig, zg = bovy_coords.XYZ_to_galcencyl(X, Y, Z)
Xg, Yg, Zg = bovy_coords.XYZ_to_galcenrect(X, Y, Z)
vRg, vTg, vZg = bovy_coords.vxvyvz_to_galcencyl(
    vX, vY, vZ, Xg, Yg, Zg)

kms = 1. * u.km / u.s
kpc = 1. * u.kpc
lsys = 8. * kpc
vsys = 220. * kms

Rg = Rg * lsys
Zg = Zg * lsys
phig = phig * u.rad
vRg = vRg * vsys
vTg = vTg * vsys
vZg = vZg * vsys

orb = Orbit(vxvv=[Rg, vRg, vTg, Zg, vZg, phig])
print orb.L()
```

This prints
```
[[    0.     0.  1760.]]
```

I usually think of the angular momentum of the Milky Way disk as pointing to the South Galactic Pole, following the right-handed rule, so by this definition the Z-component would be negative.  But it's positive in the output here.

This is all semantics and definitions I suppose...but if not understood correctly by the user can lead to incorrect signs.

**Comment by jobovy** [comment]
Hi Mark,

Okay, ``galpy`` works in a left-handed coordinate frame, so I think this is consistent with the angular momentum being a pseudo-vector, no? I don't think this has really tripped anybody up so far (as far as I know), but I guess I could add something to the introduction of the documentation about this if you think it would be useful?

**Comment by fardal** [comment]
I think it would be helpful to _some people_ (ahem - or at least former me) to mention that Galactocentric x/y/z are in a left-handed system.  And also the consequence that **L** is computed with a left-handed rule, so that disk star **L** points to the NGP.  Perhaps in the "closer look at orbits" and/or "body_conversion" sections if you don't want it up front.

**Comment by fardal** [comment]
Wow, it’s the commemorative “Mark’s an idiot” warning…  emoji are insufficient…

Happy holidays,
Mark
