### ISSUE TITLE
Importing seaborn

### ISSUE THREAD

**Issue by balbinot** [jobovy/galpy#296]
Importing seaborn on bovy_plot.py causes it to change matplotlib stylesheet scriptwide. 

For instance a simple call to
`from galpy import Orbit`

Will change the stylesheet of any plot done after that, even if is not called from within galpy (e.g. Orbit.plot).

This is fixed by
```
   import seaborn                                                               
   seaborn.reset_orig() 
```

This is not exactly an issue, but it can cause some trouble.

**Comment by jobovy** [comment]
Yes, to me this is a *feature*, simply importing bovy_plot sets the correct style sheet for how I think figures should look in papers (I don't like the default seaborn style). I think I'll just add your fix as a note in the documentation?

**Comment by balbinot** [comment]
Up to you. I opened the issue to keep this documented somewhere anyhow.

**Comment by jobovy** [comment]
Re-opened by [a snarky remark](https://twitter.com/davidwhogg/status/887698229521002496) by @davidwhogg on twitter.

**Comment by davidwhogg** [comment]
😄

**Comment by davidwhogg** [comment]
but seriously I heard several complaints at #GaiaSprint. Can't tell how serious any of them were!

**Comment by jobovy** [comment]
It's very frustrating how people will just complain about code, without opening an issue or even emailing about it. It's not like this code is unresponsive to issues (with >250 closed issues and only a few open ones). 😞

**Comment by davidwhogg** [comment]
I know! Believe me, I know.
