### ISSUE TITLE
Compilation fails on MacOS X

### ISSUE THREAD

**Issue by astrofrog** [jobovy/galpy#298]
On MacOS X 10.11, ``python setup.py build`` fails with:

```
/Users/tom/usr/bin/clang -fno-strict-aliasing -I/Users/tom/miniconda3/envs/py27/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Igalpy/util -Igalpy/util/interp_2d -Igalpy/potential_src/potential_c_ext -I/Users/tom/miniconda3/envs/py27/include/python2.7 -c galpy/util/bovy_symplecticode.c -o build/temp.macosx-10.7-x86_64-2.7/galpy/util/bovy_symplecticode.o -fopenmp -D GSL_MAJOR_VERSION=1
clang: error: unsupported option '-fopenmp'
error: command '/Users/tom/usr/bin/clang' failed with exit status 1
```

**Comment by jobovy** [comment]
I believe this should be avoided by doing
```
python setup.py build --no-openmp
```
see [the installation FAQ](http://galpy.readthedocs.io/en/latest/installation.html#i-m-having-issues-with-openmp). I thought this wasn't an issue anymore with more recent versions of clang (I use clang and don't have this problem).

**Comment by jobovy** [comment]
Please close this if this fixed the issue. If not, please provide some more information.

**Comment by astrofrog** [comment]
Works - thanks!
