### ISSUE TITLE
Miyamoto-Nagai with scalar R and vector z

### ISSUE THREAD

**Issue by fardal** [jobovy/galpy#299]
MiyamotoNagaiPotential doesn't like the combination of scalar R and array-like z.

```
>>> from galpy.potential import MiyamotoNagaiPotential, evaluatezforces
>>> pot = MiyamotoNagaiPotential(a=5., b=0.1, normalize=True)
>>> z = np.linspace(0., 10., 20)
>>> force = evaluatezforces(pot, 0., z)
...
  File "/Users/fardal/sw/lib/python2.7/site-packages/galpy-1.2-py2.7-macosx-10.6-x86_64.egg/galpy/potential_src/MiyamotoNagaiPotential.py", line 124, in _zforce
    if isinstance(R,float) and sqrtbz == asqrtbz:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I'm not exactly sure why the `if` is necessary - apparently to prevent `nan`, but can you get that under normal conditions?

In any case one possible solution would be substitute this line:
```
        if nu.all(sqrtbz == asqrtbz):
```
or this:
```
        if nu.isscalar(R) and nu.isscalar(z) and sqrtbz == asqrtbz:
```

There are four `if` tests in the module.

I apparently made the second version of this change in my local copy of galpy way back in 2014, but managed to lose it when moving to a new machine...

**Comment by jobovy** [comment]
Doesn't 
```
force = evaluatezforces(pot, numpy.zeros_like(z), z)
```
work? 

I would be happy with a pull request that allows all potentials to work with array input, but this is not a priority for me.
