### ISSUE TITLE
differential rotation 

### ISSUE THREAD

**Issue by oguzhanatas** [jobovy/galpy#301]
Hi Bovy,
are there including differential rotation in the milky way potential?

**Comment by jobovy** [comment]
I'm not sure what you mean. The ``MWPotential2014`` is made up of three potentials (bulge, disk, halo, see [section 3.5 of this paper](https://arxiv.org/abs/1412.3451). All of these individually have differential rotation and the combination of the three does too (the combination's rotation curve is approx. flat).

**Comment by oguzhanatas** [comment]
This answer what i want. Thank you.
