### ISSUE TITLE
Incorrect Rzderiv for FerrersPotential

### ISSUE THREAD

**Issue by jobovy** [jobovy/galpy#319]
The mixed radial,vertical derivative for the FerrersPotential appears to be wrong. Compare
```
>>> from galpy.potential import FerrersPotential
>>> from scipy.misc import derivative
>>> fp= FerrersPotential(normalize=1.)
# galpy Rzderiv
>>> fp.Rzderiv(0.5,0.2,phi=1.)
-1.2820755238534391
>>> # numerical from galpy zforce
>>> derivative(lambda x: -fp.zforce(x,0.2,phi=1.),0.5,dx=10.**-8.)
-3.8076983677193255
>>> # numerical from galpy Rforce
>>> derivative(lambda x: -fp.Rforce(0.5,x,phi=1.),0.2,dx=10.**-8.)
-3.8076983788215557
```
This seems to be related to the non-zero ``phi``, because ``phi=0.`` works:
```
>>> fp.Rzderiv(0.5,0.2,phi=0.)
-7.6209376873369736
>>> derivative(lambda x: -fp.zforce(x,0.2,phi=0.),0.5,dx=10.**-8.)
-7.6209377031233316
```

**Comment by jobovy** [comment]
Excluded FerrersPotential from Rzderiv test and added issue-specific test in 140a06ffadce0f22477dc5d301a995b447678acf

**Comment by jobovy** [comment]
@smoh --- I believe you wrote this part of the ``FerrersPotential`` code, could you take a look at the ``Rzderiv``?

**Comment by smoh** [comment]
Yes, I can! I'll get back to you in a few days.

**Comment by jobovy** [comment]
Thanks!
