### ISSUE TITLE
Sampling DF cannot returnOrbit

### ISSUE THREAD

**Issue by katedaniel** [jobovy/galpy#342]
I can only sample orbits when returnROrbit and returnOrbit are set to "False".  Following the instructions exactly from the website under "Two-dimensional disk distribution functions", the first line under the heading under "Sampling data from the DF":

>>> o= dfc.sample(n=4000,returnOrbit=True,nphi=1)

I receive the following error:

galpyWarning: Using C implementation to integrate orbits

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-30739bfb7c09> in <module>()
----> 1 o= dfc.sample(n=4000,returnOrbit=True,nphi=1)

~/miniconda3/lib/python3.6/site-packages/galpy/df_src/diskdf.py in sample(self, n, rrange, returnROrbit, returnOrbit, nphi, los, losdeg, nsigma, targetSurfmass, targetSigma2, maxd, **kwargs)
   1802                 else:
   1803                     thisOrbit= Orbit([rap,0.,Lz[ii]/rap])
-> 1804                 thisOrbit.integrate(sc.array([0.,tr]),self._psp)
   1805                 if returnOrbit:
   1806                     vxvv= thisOrbit(tr)._orb.vxvv

~/miniconda3/lib/python3.6/site-packages/galpy/orbit_src/Orbit.py in integrate(self, t, pot, method, dt)
    420         if not _check_integrate_dt(t,dt):
    421             raise ValueError('dt input (integrator stepsize) for Orbit.integrate must be an integer divisor of the output stepsize')
--> 422         self._orb.integrate(t,pot,method=method,dt=dt)
    423 
    424     def integrate_dxdv(self,dxdv,t,pot,method='dopr54_c',

~/miniconda3/lib/python3.6/site-packages/galpy/orbit_src/planarOrbit.py in integrate(self, t, pot, method, dt)
    244         self.t= nu.array(t)
    245         self._pot= thispot
--> 246         self.orbit, msg= _integrateROrbit(self.vxvv,thispot,t,method,dt)
    247         return msg
    248 

~/miniconda3/lib/python3.6/site-packages/galpy/orbit_src/planarOrbit.py in _integrateROrbit(vxvv, pot, t, method, dt)
    517         this_vxvv= nu.zeros(len(vxvv)+1)
    518         this_vxvv[0:len(vxvv)]= vxvv
--> 519         tmp_out, msg= _integrateOrbit(this_vxvv,pot,t,method,dt)
    520         #tmp_out is (nt,4)
    521         out= tmp_out[:,0:3]

~/miniconda3/lib/python3.6/site-packages/galpy/orbit_src/planarOrbit.py in _integrateOrbit(vxvv, pot, t, method, dt)
    615         #integrate
    616         tmp_out, msg= integratePlanarOrbit_c(pot,this_vxvv,
--> 617                                              t,method,dt=dt)
    618         #go back to the cylindrical frame
    619         R= nu.sqrt(tmp_out[:,0]**2.+tmp_out[:,1]**2.)

~/miniconda3/lib/python3.6/site-packages/galpy/orbit_src/integratePlanarOrbit.py in integratePlanarOrbit_c(pot, yo, t, int_method, rtol, atol, dt)
    345     #Set up the C code
    346     ndarrayFlags= ('C_CONTIGUOUS','WRITEABLE')
--> 347     integrationFunc= _lib.integratePlanarOrbit
    348     integrationFunc.argtypes= [ndpointer(dtype=nu.float64,flags=ndarrayFlags),
    349                                ctypes.c_int,

AttributeError: 'NoneType' object has no attribute 'integratePlanarOrbit'

**Comment by jobovy** [comment]
Apologies for the slow reply, I was away for two weeks without email.

I think you get this error because you don't have the compiled C extensions and there is a bug in the code that means that for 2D orbits in the plane the lack of C extension makes the integration fail. I have opened that as a separate issue, #343. Once that is closed you can try again using the latest master version. Alternatively, you can try getting the C extensions to compile or install. If you install the conda version on Mac or Linux, the C extensions should automatically work.

**Comment by jobovy** [comment]
Now that #343 is fixed, this error should probably have gone away if you [install the latest master version](http://galpy.readthedocs.io/en/latest/installation.html#latest-version). Please test and let me know whether this resolved the issue.

**Comment by katedaniel** [comment]
Hi Jo,

This issue is resolved and galpy is running smoothly.  Thank you so much!
