### ISSUE TITLE
Raise warning when r < minr in ChandrasekharDynamicalFrictionForce?

### ISSUE THREAD

**Issue by jobovy** [jobovy/galpy#356]
When ``r < minr``, dynamical friction is turned off, which may come as a surprise when looking at orbits at small ``r``. Perhaps raising a warning in this case would be best.

**Comment by ritzvik** [comment]
Since it's a good first issue, may I take this up?

**Comment by jobovy** [comment]
Sure! Please work in a branch of a fork and only make changes directly related to this issue.
