### ISSUE TITLE
ActionAngleAdiabatic returns JR=0 for certain [R,vR,vT] in MWPotential2014

### ISSUE THREAD

**Issue by jamesmlane** [jobovy/galpy#361]
When supplying an ```actionAngleAdiabatic``` object initialized with ```MWPotential2014``` with very specific ```[R,vR,vz]``` it returns JR=0 unexpectedly. Values in the immediate vicinity appear to work properly. The problem only appears to occur when ```c=True``` is set during initialization.

Code to replicate the issue:
```
from galpy import potential
from galpy import actionAngle
from astropy import units as apu

aA_adi = actionAngle.actionAngleAdiabatic(pot=potential.MWPotential2014, c=True) 
aA_adi_NoC = actionAngle.actionAngleAdiabatic(pot=potential.MWPotential2014)

R = 8.7007*apu.kpc
vT = 188.5*apu.km/apu.s

aA_adi(R, -0.1*apu.km/apu.s, vT, 0, 0) #Returns JR = 0.014.. <- correct 
aA_adi(R, -0.09*apu.km/apu.s, vT, 0, 0) #Returns JR = 0
aA_adi(R, -0.03*apu.km/apu.s, vT, 0, 0) #Returns JR = 0.014.. again

aA_adi_NoC(R, -0.09*apu.km/apu.s, vT, 0, 0) #Returns JR = 0.014..
```

**Comment by jobovy** [comment]
After looking into this, it seems like for this orbit the peri/apocenter are being determined incorrectly: in a bunch of if statements, the case that this orbit falls in was missed, so rperi and rapo just stayed their randomly initialized values.

I've pushed a fix to branch `fix361` that treats the cases differently and shouldn't drop any cases any longer.

I *think* actionAngleStaeckel's code is prone to similar issues, so may also have to be re-written if this fix works.

**Comment by jobovy** [comment]
actionAngleStaeckel's code's similar issue now also fixed in 59eec24

**Comment by jamesmlane** [comment]
Can confirm that this has fixed the issue presented in the code above:

```
...
aA_adi(R, -0.1*apu.km/apu.s, vT, 0, 0) #Returns JR = 0.014.. <- correct 
aA_adi(R, -0.09*apu.km/apu.s, vT, 0, 0) #Returns JR = 0.014.. <- correct now too
...
```

**Comment by jobovy** [comment]
Wonderful! I'll merge in the fix then!
