### ISSUE TITLE
Skycoord equivalency

### ISSUE THREAD

**Issue by nstarman** [jobovy/galpy#372]
The galcen_v_sun property of Orbits.SkyCoord() needs to be manually set to have Skycoord equivalency with something in the same frame.

```python
o1 = Orbits(...)
o1.integrate(...)

o2 = Orbits(vxvv=o1(o1.time()[-1]))  # initialized at end
o2integrate(...)

sc1 = o1.SkyCoords(o1.time())
sc2 = o2.SkyCoords(o1.time())
sc2.transform_to(sc1)

sc2.is_equivalent_frame(sc1)  # this returns False

sc2.galcen_v_sun = sc1.galcen_v_sun
sc2.is_equivalent_frame(sc1)  # this returns True
```

**Comment by jobovy** [comment]
Could you post a full working example? I'm not entirely sure what the issue is from this. Is ``sc1.galcen_v_sun`` different from ``sc2.galcen_v_sun`` before setting them equal? ``o2.SkyCoord`` should be setting ``v_sun``.

Also, the correct way to get ``o2`` would be
```
o2= o1(o1.time()[-1])
```

**Comment by nstarman** [comment]
I start a second orbit at the end of the 1st orbit and keep integrating. The SkyCoords should be able to be concatenated easily into one continuous SkyCoord, but this requires overriding the `galcen_v_sun` property. If this is done, then the SkyCoords may be concatenated.

```python
from astropy.coordinates import SkyCoord
from astropy import units as u
import numpy as np
from galpy.orbit import Orbits
from galpy.potential import MWPotential2014

vxvv = SkyCoord(ra=[10, 10, 10] * u.deg,
                dec=[10, 15, 20] * u.deg,
                distance=[23, 23, 23] * u.kpc,
                pm_ra_cosdec=[1, 2, 3] * u.mas / u.yr,
                pm_dec=[1, 2, 3] * u.mas / u.yr,
                radial_velocity=[0, 0, 0] * u.km / u.s)
tarr = np.linspace(0, .1, 100) * u.Gyr

o1 = Orbits(vxvv=vxvv)
o1.integrate(tarr, MWPotential2014)

o2 = Orbits(o1.SkyCoord(o1.time()[-1]))  # initialized new orbit at end of prev orbit
o2.integrate(o1.time()[-1] + tarr, MWPotential2014)

sc1 = o1.SkyCoord(o1.time())  # full skycoords
sc2 = o2.SkyCoord(o2.time())  # full skycoords
sc2.transform_to(sc1)

print(sc2.is_equivalent_frame(sc1))  # this returns False

sc2.galcen_v_sun = sc1.galcen_v_sun
print(sc2.is_equivalent_frame(sc1))  # this returns True
```

**Comment by jobovy** [comment]
I looked at this and ``o1`` and ``o2`` have the same solarmotion (actually, the V component is different at the 1e-15 level, if you do ``o2 = Orbits(o1(o1.time()[-1]))`` then they are exactly the same [there's no need to go through a SkyCoord to setup the new Orbits instance]).

I get that ``galcen_v_sun`` is exactly the same value for ``sc1`` and ``sc2`` (i.e., the difference is exactly zero), so I would consider this a bug in ``astropy``, because it tests
```
sc2.galcen_v_sun == sc1.galcen_v_sun
```
which I think is False if these are different objects, even if they have the same exact value.
