### ISSUE TITLE
Error in ttensor

### ISSUE THREAD

**Issue by webbjj** [jobovy/galpy#380]
The calculation of tzy and tzx in potential.py. There are two additional terms that should not be there. tzy and tzx can actually be set to tyz and txz, as the tidal tensor should be symmetric.

**Comment by jobovy** [comment]
Could you fix this in a branch and do a PR? Probably also best to add a test that the new behavior is correct (maybe the KeplerPotential case for z=/=0).

**Comment by jobovy** [comment]
Fixed in 5495d1d6f3de3560ef557bc459333fb72a9e5b7a
