### ISSUE TITLE
Unit conversion in array of Orbits

### ISSUE THREAD

**Issue by webbjj** [jobovy/galpy#385]
When initializing an array of orbits (o), the expected unit conversion works when calling an entire array of values (e.g o.x()) but not when calling values one by one (e.g. o[0].x()). The below code exemplifies the error.

import numpy as np
from galpy.orbit import Orbit

ra=[17.2875,302.2875,317.79583333,306.60833333,9.65833333,147.2]
dec=[61.54730278,42.86525833,17.72774722,9.45011944,-7.69072222,13.74425556]
dist=[0.16753225,0.08499065,0.03357057,0.05411548,0.11946004,0.0727802]
pmra=[633.01,119.536,-122.216,116.508,20.34,373.05]
pmdec=[65.303,540.224,-899.263,-548.329,-546.373,-774.38 ]
vlos=[-317.86,-195.44,-44.15,-246.76,-46.79,-15.17]

os=Orbit(np.column_stack([ra,dec,dist,pmra,pmdec,vlos]),radec=True,ro=8.,vo=220.,solarmotion=[-11.1,24.,7.25])
print(os.x())
print(os[0].x(),os[1].x(),os[2].x(),os[3].x(),os[4].x(),os[5].x())

**Comment by jobovy** [comment]
Fixed in ac84514e
