### ISSUE TITLE
Orbits phase-space dimensionality and SkyCoordinate

### ISSUE THREAD

**Issue by webbjj** [jobovy/galpy#386]
When using SkyCoord to setup an array of orbits (which worked in Orbits), I now get an error saying, "RuntimeError: All individual orbits in an Orbit class must have the same phase-space dimensionality".  The attached code below reproduces the error.

 Note that if I make vxvv a numpy array (currently commented out), the orbit declaration works but what is returned appears to also be full of bugs. First, the returned os is only a single orbit instance (not an array).  print(os.R()) returns the SkyCoord while print(os.pmra()) return "TypeError: unsupported operand type(s) for -: 'SkyCoord' and 'float'"

import numpy as np
from galpy.orbit import Orbit
import astropy.coordinates as coord
import astropy.units as u

ra=[17.2875,302.2875,317.79583333,306.60833333,9.65833333,147.2]
dec=[61.54730278,42.86525833,17.72774722,9.45011944,-7.69072222,13.74425556]
dist=[0.16753225,0.08499065,0.03357057,0.05411548,0.11946004,0.0727802]
pmra=[633.01,119.536,-122.216,116.508,20.34,373.05]
pmdec=[65.303,540.224,-899.263,-548.329,-546.373,-774.38 ]
vlos=[-317.86,-195.44,-44.15,-246.76,-46.79,-15.17] 

vxvv=[]
for i in range(0,len(ra)):
    vxvv.append(coord.SkyCoord(ra=ra[i]*u.degree, dec=dec[i]*u.degree, distance=dist[i]*u.kpc, pm_ra_cosdec=pmra[i]*u.mas/u.yr, pm_dec=pmdec[i]*u.mas/u.yr, radial_velocity=vlos[i]*u.km/u.s))

#vxvv=np.array(vxvv)
os=Orbit(vxvv,solarmotion=[-11.1,24.,7.25])
print(os.R())
print(os.pmra())

**Comment by jobovy** [comment]
I believe I consider both of these setups to be unsupported now (they used to work because giving a list of anything that could go to Orbit worked, but that's no longer how the code is implemented). What's the rationale for setting up like this rather than doing
```
vxvv= coord.SkyCoord(ra=ra*u.degree,dec=dec*u.degree,...)
os= Orbit(vxvv)
```
? The SkyCoord input can have arbitrary shape, but you can't give lists or arrays of them.

**Comment by webbjj** [comment]
Unsupported sounds good to me. I prefer the radec=True method anyway, just
thought I found a bug. I went down this route a couple of times since
radec=True was not supported in Orbits at one point. I also didn't know you
could send arrays to SkyCoord (not that I looked very hard at it.

Jeremy
