### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by Mohammad-Mardini** [jobovy/galpy#396]
I am a new member of the galpy club.

After installation, I tried to integrate an orbit by copy one of its examples:

`from astropy.coordinates import SkyCoord`
 `import astropy.units as u`
`c= SkyCoord(ra=20.*u.deg,dec=30.*u.deg,distance=2.*u.kpc, pm_ra_cosdec=-10.*u.mas/u.yr,pm_dec=20.*u.mas/u.yr, radial_velocity=50.*u.km/u.s)`
`o= Orbit(c)`

However, it didn't work. and I ened with the following error:

> TypeError: 'Longitude' object with a scalar value does not support indexing

Could you please help me with this issue.
Thank you in advance for your time and efforts.

**Comment by jobovy** [comment]
Which version are you using?

**Comment by Mohammad-Mardini** [comment]
galpy 1.4.1
python 2.7

**Comment by jobovy** [comment]
Thanks. The problem here is that ``astropy`` on python 2.7 doesn't support velocities (at least in a ``SkyCoord``), so this code cannot work on python 2.7. When I run this I get the error
```
ValueError: Velocity data is currently only supported in the coordinate frame objects, not in SkyCoord. See the velocities documentation page for more information: http://docs.astropy.org/en/stable/coordinates/velocities.html
```
I'm surprised you get a different error.

Anyway, upgrading to python 3 should fix this (this code works on galpy v1.4.1 under python 3). Alternatively, you can use the ``radec=True`` option in ``Orbit`` to setup the orbit with observed coordinates.

**Comment by Mohammad-Mardini** [comment]
Thank you for your prompt reply.
I installed python 3.7 on my laptop, and then galpy using the pip command. It worked!!
However, I have a new error, at the time I import galpy, as below. 



> galpyWarning: interppotential_c extension module not loaded, because of error 'dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_interppotential_c.cpython-37m-darwin.so, 6): Library not loaded: /usr/local/opt/gsl/lib/libgsl.23.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_interppotential_c.cpython-37m-darwin.so
  Reason: image not found' 
galpyWarning: integratePlanarOrbit_c extension module not loaded, because of error 'dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_integrate_c.cpython-37m-darwin.so, 6): Library not loaded: /usr/local/opt/gsl/lib/libgsl.23.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_integrate_c.cpython-37m-darwin.so
  Reason: image not found' 
galpyWarning: integrateFullOrbit_c extension module not loaded, because of error 'dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_integrate_c.cpython-37m-darwin.so, 6): Library not loaded: /usr/local/opt/gsl/lib/libgsl.23.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_integrate_c.cpython-37m-darwin.so
  Reason: image not found' 
galpyWarning: actionAngleAdiabatic_c extension module not loaded, because of error 'dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_actionAngle_c.cpython-37m-darwin.so, 6): Library not loaded: /usr/local/opt/gsl/lib/libgsl.23.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_actionAngle_c.cpython-37m-darwin.so
  Reason: image not found' 
galpyWarning: actionAngleStaeckel_c extension module not loaded, because of error 'dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_actionAngle_c.cpython-37m-darwin.so, 6): Library not loaded: /usr/local/opt/gsl/lib/libgsl.23.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/galpy_actionAngle_c.cpython-37m-darwin.so
  Reason: image not found'

**Comment by jobovy** [comment]
That indicates that the C extensions weren't properly compiled (the code will still work, just much slower, which depending on what you are trying to do might not matter). The [installation instructions](https://galpy.readthedocs.io/en/v1.4.0/installation.html) have some tips on how to deal with this issue. Installing using ``conda`` might be the easiest way to get around this.

**Comment by Mohammad-Mardini** [comment]
Thank you again for your time and efforts. I will close this issue.
