### ISSUE TITLE
evaluatelinearForces on an array of x values.

### ISSUE THREAD

**Issue by morganb-phys** [jobovy/galpy#399]
evaluatelinearForces currently only works on one position at a time (because R=1 and not an array of the same length as x). Not a real issue since it isn't supported, just a reminder.

**Comment by jobovy** [comment]
Can you post a full example of what isn't working? Just so I can make sure to fix the issue that you're having....

**Comment by morganb-phys** [comment]
It works with 1-dimensional potentials, but not ones that have been converted to 1-Dimensional potentials. For example:
`from galpy.potential import MWPotential2014, evaluatelinearForces, toVerticalPotential
import numpy as np

pot= toVerticalPotential(MWPotential2014,1.)
x= np.linspace(-1,1,11)
force= evaluatelinearForces(pot,x)`

gives an error, but 

`from galpy.potential import IsothermalDiskPotential, evaluatelinearForces, toVerticalPotential
import numpy as np

pot= IsothermalDiskPotential(1.,1.)
x= np.linspace(-1,1,11)
force= evaluatelinearForces(pot,x)`

works just fine.
