### ISSUE TITLE
Use better version parsing where specific version (scipy/astropy/...) needed

### ISSUE THREAD

**Issue by jobovy** [jobovy/galpy#407]
Currently, versions of certain packages like ``scipy`` and ``astropy`` are parsed in some of the source files using a custom version parser that does not parse all possible version strings. Switch to a more robust version, perhaps ``setuptools`` ``parse_version()``:
```
from pkg_resources import parse_version
parse_version('3.1.0-rc2') < parse_version('3.2.0')  
```
Need to then add ``setuptools`` as a dependency I think (even though ``setup.py`` uses it, but conda builds wouldn't have used ``setup.py``, so there is some chance that they wouldn't have ``setuptools``').

To close this issue, swap all version parsing to this new method.

**Comment by bsipocz** [comment]
We usually `LooseVersion` (sometimes `StrictVersion`)  all over at astropy: https://www.python.org/dev/peps/pep-0386/#distutils

**Comment by jobovy** [comment]
@bsipocz -- Thanks for the feedback! (this issue was prompted by me trying to test the ``astropy`` pre-release and finding that ``galpy`` choked.) According to what I was reading on [stackoverflow](https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python), ``distutils.version`` should not be used and ``setuptools``'s ``parse_version`` is better...

**Comment by bsipocz** [comment]
Hmm, good point. I haven't seen that being used in any of scipy stack I contribute to, though it seems to cover some corner cases that we may run into. As for parsing astropy and scipy versions, I think either way will work here equally well.

Otherwise, thanks for the pointer, https://www.python.org/dev/peps/pep-0440/ seems to be the ruling text.
