### ISSUE TITLE
galpy coordinate frame

### ISSUE THREAD

**Issue by rizman18** [jobovy/galpy#409]
In galpy v1.5.0 documentation, $3.5.4, there is a warning text that informs galpy uses a left-handed coordinate frame. 
I have a problem when I transform the coordinate of HD6755. Here is the HD6755's coordinate, based on GAIA DR2.
parallax = 5.968793155732594 mas (distance = 1 / p = 0.16753805566 kpc),
alpha = 17.435135106568044 degree,
delta = 61.54758499237452 degree,
l = 125.1106177109426 degree,
b = -1.2467162277217114 degree.

When I used galpy.util.bovy_coords.lbd_to_XYZ, I got 
X = -0.09633785057962223 kpc,
Y = 0.1370209144161999 kpc,
Z  = -0.0036452236543968383 kpc.

I'm still confused about that XYZ. 
If galpy uses left-handed and X positive towards Galactic Center (pages 401 in the documentation), Y positive will lie on l = 270 degrees. The Y position of HD6755 is positive, but the longitude (l) shows that HD6755 is on the second quadrant.

If galpy uses left-handed and X positive towards the Galactic anti center, HD6755 will be in the first or fourth quadrant, right? Because the X position of HD6755 is negative. Again, the longitude shows that it is on the second quadrant.

I think the result of galpy.util.bovy_coords.lbd_to_XYZ uses a right-handed coordinate frame with X positive towards the Galactic Center.
Can you give me an explanation for my misunderstanding? 

Thank you.

**Comment by jobovy** [comment]
I think I see what the confusion is here. The left-handed frame that is the subject of the caveats in the documentation is the *Galactocentric frame*, not the Galactic XYZ frame. The Galactic XYZ frame is, as you say, a right-handed frame. I've updated the caveats in the documentation to make this more clear.

Fun fact: you can also get the phase-space position of your star as:
```
from galpy.orbit import Orbit
o= Orbit.from_name('HD6755')
print(o.dist())
# 0.16753786355716427
```
Of course, ``Orbit.from_name`` queries SIMBAD and the Gaia data-base and may return different results at a later time, so if you want to make sure you know what you are using it's best to hard-code.

**Comment by rizman18** [comment]
Okay, thanks for your explanation. Very helpful.
