### ISSUE TITLE
Dynamical friction: ODEintWarning

### ISSUE THREAD

**Issue by nbanik** [jobovy/galpy#410]
I am trying to use dynamical friction in some orbit integrations, but I keep getting `ODEintWarning` and the output is `nan` or some nonsensical number. My code is below, I am using a const_lnLambda parameter to define the dynamical friction

    coord_radec=[266.4051, -28.936174999999995, 88.0, -0.45360437895755945, 
    -0.4083753330518072, -11.099999999999994]
    eps = 2.
    odf= Orbit(coord_radec,radec=True,ro=8.,vo=220,zo=0.0,solarmotion=[-11.1,24,7.25])

    times=np.linspace(0.,-5.,1000)/bovy_conversion.time_in_Gyr(220.,8.)   #in Gyr

    #compute spherical radius
    rr= np.sqrt(odf.x()**2 + odf.y()**2 + odf.z()**2)
    LnLambda=np.log(rr/1.4*eps) #Hashimoto
    dyn_fric=ChandrasekharDynamicalFrictionForce(GMs=6.4e10*u.Msun,const_lnLambda=LnLambd 
          a,dens=MWPotential2014)
    odf.integrate(times,MWPotential2014+dyn_fric)

> galpyWarning: Cannot use C integration because some of the potentials are not implemented in C (using leapfrog instead)
galpyWarning: Cannot use symplectic integration because some of the included forces are dissipative (using non-symplectic integrator odeint instead)
/home/nil/anaconda3/lib/python3.7/site-packages/scipy/integrate/odepack.py:247: ODEintWarning: Excess work done on this call (perhaps wrong Dfun type). Run with full_output = 1 to get quantitative information.
  warnings.warn(warning_msg, ODEintWarning)

**Comment by jobovy** [comment]
Maybe try a different Python integrator ``dop853``, because ``odeint`` sometimes gives issues (that's just scipy's standard ODE integrator).

**Comment by nbanik** [comment]
Ok, thanks Jo, changing the integration method worked.
