### ISSUE TITLE
install error with pip3.7 on mac os x.

### ISSUE THREAD

**Issue by cxwx** [jobovy/galpy#411]
ERROR: Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bp/n6k753wx1_ld0q28z0t_b90r0000gn/T/pip-install-0m1iagn0/galpy/setup.py'"'"'; __file__='"'"'/private/var/folders/bp/n6k753wx1_ld0q28z0t_b90r0000gn/T/pip-install-0m1iagn0/galpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bp/n6k753wx1_ld0q28z0t_b90r0000gn/T/pip-record-mqohb39d/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by jobovy** [comment]
I will need a little more information than this to be able to diagnose this, please send the full pip log if you can get it. Alternatively, you can try just downloading the galpy package and running ``python setup.py install`` locally, which should give all of the necessary log info.
