### ISSUE TITLE
Cannot use Orbit integration

### ISSUE THREAD

**Issue by dutry** [jobovy/galpy#423]
python-3.7.4
galpy-1.5
astropy-4.0
------------------------
For the code from the introduction: https://docs.galpy.org/en/v1.6.0/getting_started.html#orbit-integration, it shows error as follow:

<img width="728" alt="Screen Shot 2020-05-28 at 1 13 52 PM" src="https://user-images.githubusercontent.com/17509207/83101689-7dfe6380-a0e5-11ea-87d9-733cecc157c4.png">

**Comment by jobovy** [comment]
I think this was actually fixed in #407, which is included in the latest v1.6.0 release. Could you try upgrading your galpy installation to the latest version and trying again?

**Comment by dutry** [comment]
Yes!
