### ISSUE TITLE
Issue when trying to use galpy extensions 

### ISSUE THREAD

**Issue by EaleyBaley** [jobovy/galpy#429]
Hi Jo Bovy, 

I tried to use one of your codes to do a project and I stumbled upon this when running 
galpyWarning: libgalpy C extension module not loaded, because libgalpy.cp38-win32.pyd image was not found

I tried to ignore it but the code doesn't run. I'm using a windows, so how should I clear up this issue. 

Thanks

**Comment by jobovy** [comment]
This means that the C extension was not compiled during installation. However, unless you are using one of a very small number of features that isn't supported by the Python-only version, the code should still run (it should just be slower).

To help you out, please give me the following information:
* galpy version (``import galpy; print(galpy.__version__)``)
* How did you install galpy? (from source? using pip or conda?)
* Did you install the GSL (if necessary, see the docs)?

**Comment by EaleyBaley** [comment]
I installed it using pip, and yes i did install GSL. The code did eventually work, thank you so much.
