### ISSUE TITLE
Escape velocity in McMillan potential

### ISSUE THREAD

**Issue by fredifqh** [jobovy/galpy#435]
I get `nan` for the escape velocity value in the McMillan potential and the next warning:

/home/fredi/anaconda3/lib/python3.8/site-packages/galpy/potential/SCFPotential.py:224: RuntimeWarning: overflow encountered in power
  phi[:,:] = - (r*a)**l/ ((a + r)**(2*l + 1.)) * CC[:,:]* (4*numpy.pi)**0.5

/home/fredi/anaconda3/lib/python3.8/site-packages/galpy/potential/SCFPotential.py:224: RuntimeWarning: invalid value encountered in true_divide
  phi[:,:] = - (r*a)**l/ ((a + r)**(2*l + 1.)) * CC[:,:]* (4*numpy.pi)**0.5

After run:
```
from galpy.potential import vesc
from galpy.potential.mwpotentials import McMillan17
vesc(McMillan17, R=8*u.kpc)
```

**Comment by jobovy** [comment]
Should work fine now in `master`!
