### ISSUE TITLE
Orbit parameters with astropy units.

### ISSUE THREAD

**Issue by webbjj** [jobovy/galpy#439]
Hi Jo

Reem tried running a code similar to the following:

```
import astropy.units as u
from galpy.orbit import Orbit
from galpy.potential import MWPotential2014
import numpy as np

o=Orbit()
ts=np.linspace(0,1,100)*u.Gyr
o.integrate(ts,MWPotential2014)
print(o.vR(0.)) # this works
print(o.vR(0.*u.Gyr)) # this does not
```

The last print statement returns the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-110-961121ed608a> in <module>
      8 o.integrate(ts,MWPotential2014)
      9 print(o.vR(0.))
---> 10 print(o.vR(0.*u.Gyr))

/usr/local/lib/python3.7/site-packages/galpy-2.0.dev0-py3.7-macosx-10.14-x86_64.egg/galpy/util/bovy_conversion.py in wrapped(*args, **kwargs)
    679                     if _apy_units:
    680                         u= units.dimensionless_unscaled
--> 681                 out= method(*args,**kwargs)
    682                 if out is None:
    683                     return out

/usr/local/lib/python3.7/site-packages/galpy-2.0.dev0-py3.7-macosx-10.14-x86_64.egg/galpy/orbit/Orbits.py in shape_wrapper(*args, **kwargs)
    145     def shape_wrapper(*args,**kwargs):
    146         dontreshape= kwargs.get('dontreshape',False)
--> 147         result= func(*args,**kwargs)
    148         if dontreshape:
    149             return result

/usr/local/lib/python3.7/site-packages/galpy-2.0.dev0-py3.7-macosx-10.14-x86_64.egg/galpy/orbit/Orbits.py in vR(self, *args, **kwargs)
   2939 
   2940         """
-> 2941         return self._call_internal(*args,**kwargs)[1].T
   2942 
   2943     @physical_conversion('velocity')

/usr/local/lib/python3.7/site-packages/galpy-2.0.dev0-py3.7-macosx-10.14-x86_64.egg/galpy/orbit/Orbits.py in _call_internal(self, *args, **kwargs)
   4236         # where one wants all integrated times
   4237         t_exact_integration_times= hasattr(t,'__len__') \
-> 4238             and (len(t) == len(self.t)) \
   4239             and numpy.all(t == self.t)
   4240         if _APY_LOADED and isinstance(t,units.Quantity):

/usr/local/lib/python3.7/site-packages/astropy/units/quantity.py in __len__(self)
   1068         if self.isscalar:
   1069             raise TypeError("'{cls}' object with a scalar value has no "
-> 1070                             "len()".format(cls=self.__class__.__name__))
   1071         else:
   1072             return len(self.value)

TypeError: 'Quantity' object with a scalar value has no len()

Not sure if a bug or not possible to use astropy units with time when calling o.vR(). Thought it was worth bringing to your attention.

Jeremy

**Comment by jobovy** [comment]
This should work and it works for me, so I suspect that this might be because of a change in a more recent version of astropy? What version of astropy are you/Reem using?

**Comment by webbjj** [comment]
I am using astropy 4.0.

**Comment by webbjj** [comment]
Just tried on the server and it doesn't work either using astropy version 3.1.2

**Comment by jobovy** [comment]
Thanks! Apparently I'm on astropy 4.0.2; I also tried on the server (both servers) and this code does work for me.

I think this might be because you are using an older version of `galpy`, I think I fixed this [here](https://github.com/jobovy/galpy/commit/a42411fae14f4d7d0d827605034e999d04e0c1b9).

**Comment by webbjj** [comment]
Updating galpy and astropy was the fix. Reem had the latest galpy but an older astropy, I had the opposite.
