### ISSUE TITLE
Error in documentation for Orbit.integrate

### ISSUE THREAD

**Issue by mwbub** [jobovy/galpy#441]
Currently the documentation for `Orbit.integrate` lists "dopr853_c" for the 8-5-3 Dormand-Prince integrator, but in the source code the corresponding method is "dop853_c", without the 'r'. The documentation also does not list the Python implementation of the same integrator.

**Comment by mwbub** [comment]
Also, I notice that for potentials without a C implementation, dop853_c currently defaults to odeint rather than dop853, but I'm not sure whether this is intentional or not.

**Comment by jobovy** [comment]
Thanks, this is true! This is only an issue in the API docs, right? I think the part of the 'Quickstart guide' has the right names...

Yes, non-C potentials always fall back to `odeint`, which is generally faster than `dop853`.

**Comment by mwbub** [comment]
Yeah, I only noticed the issue in the API docs, although I haven't exhaustively looked through the quickstart guide by any means.
