### ISSUE TITLE
Divergent shell masses for PowerSphericalPotentialwCutoff when slope >= 3

### ISSUE THREAD

**Issue by jamesmlane** [jobovy/galpy#452]
Power law potentials (`PowerSphericalPotential`, `TwoPowerSphericalPotential`, `PowerSphericalPotentialwCutoff`) have divergent mass when the inner slope `alpha>=3`. For `PowerSphericalPotential` and `TwoPowerSphericalPotential` the analytic mass formulae are given assuming boundary conditions (occuring at `r=0`) evaluate to 0. This results in behaviour where, for `alpha>=3`, the mass of these potentials is unphysically negative,  but the shell mass evaluates correctly. This is the case for both analytic and forced integration using Gauss theorem:

``` python
from galpy import potential
psp = potential.PowerSphericalPotential(alpha=3.5)
psp.mass(2.) # a negative number - unphysical
psp.mass(2.)-psp.mass(1.) # The correct, positive value
```

`PowerSphericalPotentialwCutoff` does not behave in this way.

``` python
from galpy import potential
pspwc = potential.PowerSphericalPotentialwCutoff(alpha=3.5,rc=5.)
pspwc.mass(2.) # np.nan, reflects divergent mass
pspwc.mass(2.)-pspwc.mass(1.) # Also np.nan
```

This is because the radial force for `PowerSphericalPotentialwCutoff` is calculated most straightforwardly using an incomplete gamma function. The `scipy` implementation of incomplete gamma functions are regularized, which can never be evaluated for `alpha>=3`, which requires evaluating `scipy.special.gamma(x)` where `x<0` which returns `np.nan`. A better solution could be to formulate the cases where `alpha<3` using a hypergeometric function. The exponential integral `scipy.special.expn` could also be used, but it's numerical accuracy seems to be too poor for general use. The ideal behaviour would be a fast mass calculator for `alpha<=3` that returns the correct, finite shell mass. Unphysical, negative total mass is not ideal, but would put behaviour inline with other power law potentials.

**Comment by jobovy** [comment]
Fixed in fe148282c0b9af801f405b3320518af3f73ead2e.
