### ISSUE TITLE
Time-depended potential model

### ISSUE THREAD

**Issue by alfaniadiva** [jobovy/galpy#456]
Hello
I want to plot orbit integration with the time-depended potential model. How to modify the potential model in galpy so it becomes a function of time? For example, I want to change the "amp" parameter in Hernquist potential as a function of time.

Thank you

**Comment by jobovy** [comment]
Hi!

Changing the amplitude of a potential is most easily done with a [wrapper potential](https://docs.galpy.org/en/latest/potential.html#modifying-potential-instances-using-wrappers). Currently, the only implemented amplitude change is the [`DehnenSmoothWrapperPotential`](https://docs.galpy.org/en/latest/reference/potentialdehnensmoothwrapper.html), which allows you to grow or decay the amplitude in a particular way. If that works for you, you should be able to get it working using the documentation. If you need another form, it's pretty easy to implement a new wrapper potential following the code for the `DehnenSmoothWrapperPotential` and then it would work in Python (which should be fast enough unless you are integrating many orbits).

**Comment by alfaniadiva** [comment]
Thank you for the answer!
