### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by mlldantas** [jobovy/galpy#461]
Hi there!

I just wanted to let you know I am using your package galpy and I received an important deprecation warning. Maybe it's time to check and update the code.

> /work/mlldantas/anaconda3/lib/python3.8/site-packages/galpy/potential/SCFPotential.py:292: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
>   func[j] = numpy.sum(self._compute(funcTilde, R[j][0],z[j][0],phi[j][0]))
> 
> /work/mlldantas/anaconda3/lib/python3.8/site-packages/galpy/potential/SCFPotential.py:228: RuntimeWarning: overflow encountered in power
>   phi[:,:] = - a**l*r**(-l-1.)/ ((1.+a/r)**(2*l + 1.)) * CC[:,:]* (4*numpy.pi)**0.5

Thanks! :smiley:

**Comment by jobovy** [comment]
Thanks for reporting these, they should now be fixed.
