### ISSUE TITLE
Question regarding disparity between manually-calculated potentials vs. galpy potentials

### ISSUE THREAD

**Issue by callous4567** [jobovy/galpy#462]
I'm planning to use galpy in my MSc work, using a Hernquist Bulge, M-Nagai Disk, and NFW Halo profile. I've set up all three with the parameters I plan to use (https://arxiv.org/pdf/1812.00846.pdf) and have evaluated the potential for my dataset- the results look like what might be expected. 

When I evaluate the potentials with the potentials written out explicitly (rather than relying on galpy) however, I end up with different values. 

As an example, the function I'm using to manually ascertain the Hernquist potential is (http://articles.adsabs.harvard.edu/pdf/1990ApJ...356..359H) 

\Phi = -\frac{GM_b}{r + a} 

where for the equivalent galpy potential (https://docs.galpy.org/en/v1.7.1/reference/potentialhernquist.html) I've set amp (using iau2015 units from astropy) to 2GM_b via
`amp = 2*M_b*iau.GM_sun` 
and am using the same value of a, also in units of kpc. In my case for example position of [x,y,z] kpc = [1,2,3] kpc, galpy yields ~-4e3 while manual yields -29e3, which is quite a big difference... 

For reference, I'm instantiating the potential via 
`self.bulge = potential.HernquistPotential(amp=amp_hernquist,
                                                  a=a_b*u.kpc,
                                                  normalize=False,
                                                  ro=ro*u.kpc,
                                                  vo=vo*u.km/u.s)`
where ro/vo are different from default (but only slightly) and dimensionless in this context.  

This isn't necessarily something that contributes to the galpy project in any sort, but, would it be possible to know whether I'm at fault in how I'm calculating the potential, or in how I'm instantiating the potential from galpy, or maybe in interpreting the output?

**Comment by jobovy** [comment]
Hi,

This probably has something to do with the units, either of the inputs or the output. Could you send a full, self-contained example so I can try to see what's going on?

**Comment by callous4567** [comment]
> Hi,
> 
> This probably has something to do with the units, either of the inputs or the output. Could you send a full, self-contained example so I can try to see what's going on?

Thanks for the quick reply! ^.^
Here's my working example just for Hernquist

```import galpy.potential as potential
import astropy.units as u
import astropy.constants.iau2015 as iau
import numpy as np

# Hernquist Bulge. Mass in solmas. Scale in kpc.
M_b = 3e10 # bulge mass
a_b = 0.7 # radial scale

# Specify custom ro/vo
ro = 8.178
vo = 245.6

# Example coordinate to test
x, y, z = 1, 2, 3
xx, yy ,zz = x*u.kpc, y*u.kpc, z*u.kpc

# Cylindrically- galpy doesn't seem to want quantities for R and z.
R = np.sqrt(x**2 + y**2)

# Hernquist Potential. Takes quantities.
def hernquist(x, y, z):
    r = np.sqrt(x**2 + y**2 + z**2)
    return (-iau.GM_sun*M_b/(r + (a_b*u.kpc))).to(u.km**2/u.s**2)

# Galpy Potential.
amp_hernquist = 2*M_b*iau.GM_sun
bulge = potential.HernquistPotential(amp=amp_hernquist,
                                     a=a_b*u.kpc,
                                     normalize=False,
                                     ro=ro*u.kpc,
                                     vo=vo*u.km/u.s)

# Evaluate using manual method/galpy method
manual = hernquist(xx, yy, zz)
galpy = potential.evaluatePotentials(bulge, R=R, z=z)
print(manual, galpy)
```

**Comment by jobovy** [comment]
The problem here is that when you provide `R` and `z` without units (that is, not as a Quantity), then the code assumes they are in internal units, in this case in units of `ro`. You write "galpy doesn't seem to want quantities for R and z", but that's not true, you should do
```
R = np.sqrt(xx**2 + yy**2)
galpy = potential.evaluatePotentials(bulge,R,zz)
```
Note that you can't write `R=R` and `z=zz`, that's why your input was incorrectly parsed when you tried this with units.

The call sequence is to take `R` and `z` as arguments, not as keywords. Unfortunately, Python decided to allow arguments to be specified as keywords and it's impossible to disallow this, leading to these kinds of issues...

**Comment by callous4567** [comment]
> The problem here is that when you provide `R` and `z` without units (that is, not as a Quantity), then the code assumes they are in internal units, in this case in units of `ro`. You write "galpy doesn't seem to want quantities for R and z", but that's not true, you should do
> 
> ```
> R = np.sqrt(xx**2 + yy**2)
> galpy = potential.evaluatePotentials(bulge,R,zz)
> ```
> 
> Note that you can't write `R=R` and `z=zz`, that's why your input was incorrectly parsed when you tried this with units.
> 
> The call sequence is to take `R` and `z` as arguments, not as keywords. Unfortunately, Python decided to allow arguments to be specified as keywords and it's impossible to disallow this, leading to these kinds of issues...

Ah, that makes sense- I assumed that galpy was taking them in (without units) as kpc- I've definitely misunderstood the Intro page! Thanks for clarifying that-

I've not had any courses that have taught good coding etiquette and I've always (since I've only ever used Python) used keywords to specify arguments- I'm assuming this isn't universal and is likely frowned upon in other languages? I'll keep that in mind in the future (both when using galpy and writing code myself)

Thanks again :D
