### ISSUE TITLE
[Feature Request] Add `.pre-commit-config.yml`

### ISSUE THREAD

**Issue by SauravMaheshkar** [jobovy/galpy#463]
I noticed that most of (if not all) the steps of the Contributing wiki can be automated via [**pre-commit**](https://pre-commit.com/). Having [**pre-commit**](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions.

I'd be more than happy to take this up.

**Comment by SauravMaheshkar** [comment]
CC: @jobovy

**Comment by jobovy** [comment]
Thanks for opening this issue, but I have no interest in adding pre-commit hooks at this point.
