### ISSUE TITLE
Implement adaptive timesteps and block timestep

### ISSUE THREAD

**Issue by User087** [jobovy/galpy#464]
Suggestions:
Allow the user to specifiy a criterion according to which the particle's timestep is to be adapted, e.g. reducing the timestep as the acceleraiton of the particle grows larger, like: (dt_old) × (dt_new) <= k/a for some constant k and where a is the acceleration of the particle, dt_old is the timestep used to evolve to the current acceleration a and dt_new is the timestep used to evolve from it. An alternative if you can't allow the user to specify a criterion would be to implement a set of criteria which the user can choose from, like the set of integrators implemented.
Also, enable the use of a block timestep so the particles can be placed according to their timestep on e.g. rungs in powers of two: dt = (dt_max)/(2^n).

**Comment by jobovy** [comment]
Thanks for the suggestion, I'd be happy to review a PR along these lines. Note that some of the integrators already have adaptive time steps (the Dormand-Prince ones).
