### ISSUE TITLE
Problem with parallel_map (from galpy/util/multi.py) and bovy_coords functions

### ISSUE THREAD

**Issue by wilmatrick** [jobovy/galpy#468]
Hi Jo, hi galpy users,

for the first time in 8 years of using it, Jo's very convenient parallel_map() throws a weird and unpredictable error message I cannot debug myself.

Did anyone ever come across something similar?

_________The error message is:_________
Traceback (most recent call last):
  File "[...]/galpy/util/multi.py", line 185, in parallel_map
    return run_tasks(procs, err_q, out_q, numcores)
  File "[...]/galpy/util/multi.py", line 126, in run_tasks
    return list(numpy.concatenate(results))
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: zero-dimensional arrays cannot be concatenated

_________When & where does the error occur?_________
The general usage is: out = multi.parallel_map(lambda x: parallel_function(x),range(120),numcores=40)
The error does not occur if I run a for-loop over parallel_function(x) on a single core.
By commenting out parts of the code in parallel_function(), I found that the error might be related to the use of Jo's convenience bovy_coords functions, e.g. bovy_coords.vrpmllpmbb_to_vxvyvz() and (possibly?!?!?!) large numpy arrays.

I do know that debugging my specific code is not the task of this forum. ;-)
I just wanted to ask if someone knows from their own experience why and when above error message could appear?

I would be grateful for any pointers!

(Quite desperate) Cheers,
Wilma

**Comment by jobovy** [comment]
Hi WIlma! I've seen this type of error many times and it normally means that there is some error in the `parallel_function`. If that errors for some `x`, the concatenation of all of the outputs fails. You say that a for loop works, but it must be that there is some issue when running the code in parallel that's not showing up in a for loop. If you post the code, I might be able to help better.

**Comment by wilmatrick** [comment]
Hi Jo, thanks for your swift reply. 
I think I solved my issue in the meantime: I was trying to do 40 x 17 million coordinate transformations (on 40 cores) in parallel. I presume that was just too much memory for the machine and that's why the code crashed. (And that's also why the code worked when it was just 1 x 17 million trafos at a time....) I "solved" the issue by using a for-loop that does the trafos in batches. The only galpy-related "problem" was in the end, that parallel_map could not produce meaningful error messages for my very specific case.
But all good on my side now.
Thanks & cheers,
Wilma

**Comment by jobovy** [comment]
I somehow missed this response, but I'm glad you figured it out! Sorry that the error message wasn't more helpful! I assume I can close the issue now...
