### ISSUE TITLE
evaluateRforce with R= and z= as Quantities fails

### ISSUE THREAD

**Issue by kassidy-kollmann** [jobovy/galpy#470]
Hello! 

When I run the line: `evaluateRforces(nfw_potential,R=100*u.kpc,z=0*u.kpc)` to calculate the NFWPotential Rforce from galpy, the code breaks with the error: "UnitConversionError: Can only apply 'add' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)" .

This was not happening when I ran: `evaluateDensities(nfw_potential,R=100*u.kpc,z=0*u.kpc)`, so I looked more into the code, and I believe it is breaking because in the way that I was calling the evaluateRforces function, R and z are set as kwargs instead of args. In the potential_physical_input decorator that is supposed to convert R and z to natural units, it loops through all of the args to convert them to natural units, but it only looks at specific kwargs: phi, t, v, and M. This doesn't seem to be an issue for the evaluateDensities function because that function ultimately calls the dens function with R and z, and at this point they are args and not kwargs, so they are caught by the potential_physical_input decorator before the density is actually calculated. Running the Rforce code as: `evaluateRforces(nfw_potential,100*u.kpc,0*u.kpc)` works completely fine, but I thought I would mention this issue in case anyone else experiences it.

I am currently trying to calculate the Rforce for the Chandrasekhar Dynamical Friction Force as: `evaluateRforces(df,100*u.kpc,0*u.kpc,phi=0*u.deg,v=[vR,vT,vZ])` where v is of the form: `[<Quantity -123.40399424 km / s>, <Quantity 71.24732929 km / s>, <Quantity 0. km / s>]`. This also breaks, with the error: "UnitConversionError: 'Unit("km / s")' is not a scaled version of 'Unit(dimensionless)'". I believe that the potential_physical_input decorator is not entering the case: 
`if 'v' in kwargs and _APY_LOADED and isinstance(kwargs['v'],units.Quantity):` 
because the overall v is not a Quantity, even if each individual v[0], v[1], v[2] is. I was thinking that to fix this I could either set each component of the v input to already be in natural units and/or add a case to the potential_physical_input decorator to check if v is a list of Quantities? I wanted to mention this issue as well to make sure I wasn't missing anything and to check that this change to the conversion code would not cause any other issues with different functions.

Thank you!

**Comment by jobovy** [comment]
Thanks for the report! Evaluating with `R=` and `z=` as Quantities is a known issue (#437). According to the documentation, this is incorrect use of the code, but unfortunately Python doesn't raise an error when providing an argument as a keyword argument. As far as I know, there's no real way to guard against this. Perhaps this has now tripped up enough people that we should just bite the bullet and parse keyword `R` and `z`, because I don't think there's any harm in that.

The issue with providing `v` is similar (although perhaps the documentation isn't as clear in this case): `v` should be a vector Quantity, not a list of Quantities. So you just have to provide it as a Quantity. In your case, you can just do
```
v=units.Quantity(YOUR_V)
```
because `units.Quantity` will convert your list of Quantities to a single vector Quantity.

Let's keep this open for now to remember to fix the `R=` and `z=` issue.

**Comment by kassidy-kollmann** [comment]
Thank you for your help! I didn't realize the R= and z= was already an issue posted on here, thank you for tagging it!

**Comment by kassidy-kollmann** [comment]
Oh I also meant to ask, I see that the documentation for galpy.orbit.Orbit.integrate says that 0 has to be in the list of times t, but I am currently trying to integrate an orbit that does not include 0 using the odeint integrator and it seems to work fine. I was reading issue #390 which sounds like any issue with a nonzero initial time for another integrator was resolved. So is it fine to integrate over a time period that does not include 0?

**Comment by jobovy** [comment]
Yes, it should be fine to use a non-zero first time. I'm not sure why I wrote the docs this way, I vaguely remember that 10 years ago 0 had to be the first entry. But I think the correct statement is that the first entry is the time of the initial condition. 

Note that using `odeint` is not generally recommended. It can behave weirdly and have large errors. If you need a good Python integrator, use `dop853`. Better yet, use the C integrators if you can.
