### ISSUE TITLE
Weird radial velocities when flipping orbit

### ISSUE THREAD

**Issue by smeingast** [jobovy/galpy#481]
Hey. Just noticed that when flipping an orbit, I get very strange radial velocity readings. Here's the code to reproduce the result:

```
import numpy as np
from astropy import units as u
from astropy.coordinates import SkyCoord
from galpy.orbit import Orbit
from galpy.potential import MWPotential2014

ts = np.linspace(0, 100, 5) * u.Myr

coo = SkyCoord(
    ra=250 * u.deg,
    dec=-20 * u.deg,
    distance=250 * u.pc,
    pm_ra_cosdec=-20 * u.mas / u.yr,
    pm_dec=20 * u.mas / u.yr,
    radial_velocity=10 * u.km / u.s,
    frame="icrs",
)

o = Orbit(coo)
o.integrate(ts, MWPotential2014)

rv = o.SkyCoord(ts).radial_velocity
print(rv)
# [ 10.           7.11215027  -9.72675932 -22.65899826 -28.49652797] km / s

o.flip(inplace=True)
rv = o.SkyCoord(ts).radial_velocity
print(rv)
# [ -25.50342192 -439.74186573 -356.92852705 -244.44249105 -119.58920121] km / s
```

The same happens when reading them directly with `o.vlos(ts)`. Is this an error on my end with the orbit flipping, or is this an issue with galpy? 

Many thanks for looking into this!! 😊

**Comment by smeingast** [comment]
Ah! Alright then, thanks for the tip (and the quick reply). Is it possible that integrating with negative times has only become possible recently with galpy? I feel like I tried this a few years ago and needed to flip the orbit to make the backward integration work. 🤔
In any case, this not only fixes my problem, it also makes writing my script far easier!! :D

**Comment by jobovy** [comment]
> Is it possible that integrating with negative times has only become possible recently with galpy? I feel like I tried this a few years ago and needed to flip the orbit to make the backward integration work. 🤔 

I don't quite remember, but I think there used to be issues with integrating backward with negative times. I don't remember what they were though... Anyway, it should now work and please open an issue if it doesn't!
