### ISSUE TITLE
specify solarmotion in streamspraydf

### ISSUE THREAD

**Issue by webbjj** [jobovy/galpy#482]
When calling `streamspraydf.sample` with `return_orbit=True`, it would be ideal to be able to specify `solarmotion` for when the orbit is initialized and/or have it inherited from the progenitor's orbit.

**Comment by jobovy** [comment]
Thanks for opening, great point about inheriting from the progenitor's orbit!

**Comment by jobovy** [comment]
Went for inheriting from the input `progenitor` orbit, which I think is the most logical setting, but let me know if this doesn't fully solve your issue.
