### ISSUE TITLE
Question about differences in NFWPotential densities from galpy evaluateDensities and manually calculated density?

### ISSUE THREAD

**Issue by taliaoshea** [jobovy/galpy#483]
Hi there! 
When evaluating the densities of an NFW potential in two different ways the curves do not seem to match up (as shown in attached plot). The first way uses the equation for the NFW density at the top of this page (blue curve), and the other uses galpy.potential.evaluateDensities (orange curve). Do you know why the shapes of these two curves do not align and the output of these methods is different? The code is also attached. Thank you so much!!
![nfwDensitiesNoMatch](https://user-images.githubusercontent.com/87497123/171266558-4c3fe21e-beb4-4382-916b-dd7385a406f0.png)
```
import numpy as np
import matplotlib.pyplot as plt
import galpy.potential
from galpy.orbit import Orbit
from astropy import units as u
from galpy.potential import NFWPotential

d = np.logspace(-2,2,200)*u.Mpc

#defining the NFWPotential
nfw = NFWPotential(conc=1.,mvir=100.,H=70.0,Om=0.3,overdens=200.,wrtcrit=False)

#density from the analytical expression at the top of
# https://docs.galpy.org/en/v1.7.1/reference/potentialnfw.html
aVal = nfw.a*u.kpc
amp = nfw._amp*u.Msun

rho = (amp)/(4*np.pi*(aVal**3)*(d/aVal)*(1+(d/aVal))**2)

scaleFactor = 0.1
plt.plot(d, rho*scaleFactor,label='nfw density from equation, scaled x'+str(scaleFactor))

#density from evaluateDensities
dens = galpy.potential.evaluateDensities(nfw,d,0)
plt.plot(d,dens,label='nfw density with evaluateDensities')
```

**Comment by jobovy** [comment]
The issue here is that the units of `a` and `amp` don't match in the two different ways. The shape is wrong because `nfw.a` is in internal units, so physical units are 
```
aVal= nfw.a*8.*u.kpc
```
The amplitude is also in internal units, so to get it in Msun you need to do
```
from galpy.util import conversion
amp = nfw._amp*u.Msun*conversion.mass_in_msol(220.,8.)
```

Then the expressions match. However, depending on your `galpy` configuration, `evaluateDensities` might or might not return a `Quantity`, so to be absolutely sure do
```
rho = (amp)/(4*np.pi*(aVal**3)*(d/aVal)*(1+(d/aVal))**2)
plt.loglog(d, rho.to(u.Msun/u.pc**3.),label='nfw density from equation, scaled x'+str(scaleFactor))
#density from evaluateDensities
dens = galpy.potential.evaluateDensities(nfw,d,0,quantity=True)
plt.plot(d,dens.to(u.Msun/u.pc**3.),label='nfw density with evaluateDensities')
```

Generally, it's a bad idea to use internal quantities such as `_amp` (the underscore in the variable name indicates that it's a private variable), because they might not mean what you think they mean. Here they do (i.e,, `_amp` is actually the same `amp` as mentioned in the docs), but for other potentials the internal `_amp` is a modified amplitude (modified for convenience and/or computational reasons). The best way to get `amp` out for the NFW potential is by solving for it using the density equation.

**Comment by jobovy** [comment]
Just for fun, [here is the correct version of the code](https://www.galpy.org/repl/repl/index.html?kernel=python&prerun=import%20micropip%0A%0Aawait%20micropip.install%28%27astroquery%27%29%0A%0Aawait%20micropip.install%28%27https%3A%2F%2Fwww.galpy.org%2Fwheelhouse%2Fgalpy-latest-py3-none-any.whl%27%29%0A%0Aimport%20warnings%0A%0Afrom%20galpy.util%20import%20galpyWarning%0A%0Awarnings.simplefilter%28action%3D%27ignore%27%2Ccategory%3DgalpyWarning%29%0A%0Afrom%20astropy%20import%20units%0A%0Aimport%20astropy.units%20as%20u%0A%0Aimport%20galpy.util.conversion%0A%0Agalpy.util.conversion._APY_UNITS%3DTrue%0A%0Aimport%20galpy.orbit.Orbits%0A%0Agalpy.orbit.Orbits._APY_LOADED%3D%20True%0A%0A%25matplotlib%20inline%0A%0A&&code=import%20numpy%20as%20np%0Aimport%20matplotlib.pyplot%20as%20plt%0Aimport%20galpy.potential%0Afrom%20galpy.orbit%20import%20Orbit%0Afrom%20astropy%20import%20units%20as%20u%0Afrom%20galpy.potential%20import%20NFWPotential%0Ad%20%3D%20np.logspace%28-2%2C2%2C200%29%2Au.Mpc%0Anfw%20%3D%20NFWPotential%28conc%3D1.%2Cmvir%3D100.%2CH%3D70.0%2COm%3D0.3%2Coverdens%3D200.%2Cwrtcrit%3DFalse%29%0AaVal%20%3D%20nfw.a%2Au.kpc%2A8.%0Afrom%20galpy.util%20import%20conversion%0Aamp%20%3D%20nfw._amp%2Au.Msun%2Aconversion.mass_in_msol%28220.%2C8.%29%0Arho%20%3D%20%28amp%29%2F%284%2Anp.pi%2A%28aVal%2A%2A3%29%2A%28d%2FaVal%29%2A%281%2B%28d%2FaVal%29%29%2A%2A2%29%0Aplt.loglog%28d%2C%20rho.to%28u.Msun%2Fu.pc%2A%2A3.%29%2Clabel%3D%27nfw%20density%20from%20equation%27%29%0Adens%20%3D%20galpy.potential.evaluateDensities%28nfw%2Cd%2C0%2Cquantity%3DTrue%29%0Aplt.plot%28d%2Cdens.to%28u.Msun%2Fu.pc%2A%2A3.%29%2Clabel%3D%27nfw%20density%20with%20evaluateDensities%27%29%0A), you can just run this in your browser.

**Comment by taliaoshea** [comment]
I see, thank you so much for your quick response and help!!
