### ISSUE TITLE
Overflow error in ``McMillan17``

### ISSUE THREAD

**Issue by jobovy** [jobovy/galpy#495]
``McMillan17`` (and more generally, ``DiskSCFPotential``) is prone to overflow errors at large `z/zd`, for example, the following fails
```
import numpy as np
from galpy.orbit import Orbit
from galpy import potential
from galpy.potential.mwpotentials import McMillan17
from galpy.actionAngle import estimateDeltaStaeckel
from galpy.util import conversion
ro17 = conversion.get_physical(McMillan17)['ro']
vo17 = conversion.get_physical(McMillan17)['vo']
o17 = Orbit([209.3, 26.8, 46.5, -1.16, -0.88, 189.11], radec=True, ro = ro17, vo=vo17)
estimateDeltaStaeckel(McMillan17,o17.R(use_physical=False),o17.z(use_physical=False))
```
because of overflow in line 270 here: https://github.com/jobovy/galpy/blob/6abeaa6764b3734a64eb9baa4af2f754a41b9869/galpy/potential/DiskSCFPotential.py#L268-L270

cc @anyadovgal who raised this issue originally.

**Comment by yunpeng-jia** [comment]
Dear Dr. Jo Bovy,
The potential of McMillan17 also raised another issue at some special locations of (R,z) in Galactocentric Coordinate: 

_galpy/actionAngle/actionAngleStaeckel.py:1075: RuntimeWarning: divide by zero encountered in double_scalars
  -evaluatez2derivs(pot,R,z,use_physical=False)))/evaluateRzderivs(pot,R,z,use_physical=False))_

for example:
```
from galpy.orbit import Orbit
from astropy import units
from galpy.potential.mwpotentials import McMillan17
from galpy.actionAngle import estimateDeltaStaeckel 

o = Orbit(vxvv=[8.462* units.kpc, 0.6 * units.km / units.s, 236.1* units.km / units.s, 0.0 * units.kpc, -7.5 * units.km / units.s],ro=8.21,vo=233.1)
estimateDeltaStaeckel(McMillan17,o.R(),o.z())
```
The attached file contains 736 stars obtained from the common stars between APOGEE and Gaia that will raise this issue.
Thank you in advance!

[undetermined-jr-updatezerooffset.txt](https://github.com/jobovy/galpy/files/9554335/undetermined-jr-updatezerooffset.txt)

**Comment by jobovy** [comment]
> Dear Dr. Jo Bovy, The potential of McMillan17 also raised another issue at some special locations of (R,z) in Galactocentric Coordinate:
> 
> _galpy/actionAngle/actionAngleStaeckel.py:1075: RuntimeWarning: divide by zero encountered in double_scalars -evaluatez2derivs(pot,R,z,use_physical=False)))/evaluateRzderivs(pot,R,z,use_physical=False))_
> 
> for example:
> 
> ```
> from galpy.orbit import Orbit
> from astropy import units
> from galpy.potential.mwpotentials import McMillan17
> from galpy.actionAngle import estimateDeltaStaeckel 
> 
> o = Orbit(vxvv=[8.462* units.kpc, 0.6 * units.km / units.s, 236.1* units.km / units.s, 0.0 * units.kpc, -7.5 * units.km / units.s],ro=8.21,vo=233.1)
> estimateDeltaStaeckel(McMillan17,o.R(),o.z())
> ```
> 
> The attached file contains 736 stars obtained from the common stars between APOGEE and Gaia that will raise this issue. Thank you in advance!
> 
> [undetermined-jr-updatezerooffset.txt](https://github.com/jobovy/galpy/files/9554335/undetermined-jr-updatezerooffset.txt)

Thanks for the clear example! This happens because `estimateDeltaStaeckel` fails if evaluated exactly at z=0, so you can get around this by simply adding a very small offset to `o.z()`, for example
```
estimateDeltaStaeckel(McMillan17,o.R(),o.z()+1.*units.pc)
```
Does this fix the issue for all 736 stars that you mention? If not, let me know. I do think we should fix the z=0 NaN, because this shouldn't happen.

**Comment by yunpeng-jia** [comment]
> > Dear Dr. Jo Bovy, The potential of McMillan17 also raised another issue at some special locations of (R,z) in Galactocentric Coordinate:
> > _galpy/actionAngle/actionAngleStaeckel.py:1075: RuntimeWarning: divide by zero encountered in double_scalars -evaluatez2derivs(pot,R,z,use_physical=False)))/evaluateRzderivs(pot,R,z,use_physical=False))_
> > for example:
> > ```
> > from galpy.orbit import Orbit
> > from astropy import units
> > from galpy.potential.mwpotentials import McMillan17
> > from galpy.actionAngle import estimateDeltaStaeckel 
> > 
> > o = Orbit(vxvv=[8.462* units.kpc, 0.6 * units.km / units.s, 236.1* units.km / units.s, 0.0 * units.kpc, -7.5 * units.km / units.s],ro=8.21,vo=233.1)
> > estimateDeltaStaeckel(McMillan17,o.R(),o.z())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The attached file contains 736 stars obtained from the common stars between APOGEE and Gaia that will raise this issue. Thank you in advance!
> > [undetermined-jr-updatezerooffset.txt](https://github.com/jobovy/galpy/files/9554335/undetermined-jr-updatezerooffset.txt)
> 
> Thanks for the clear example! This happens because `estimateDeltaStaeckel` fails if evaluated exactly at z=0, so you can get around this by simply adding a very small offset to `o.z()`, for example
> 
> ```
> estimateDeltaStaeckel(McMillan17,o.R(),o.z()+1.*units.pc)
> ```
> 
> Does this fix the issue for all 736 stars that you mention? If not, let me know. I do think we should fix the z=0 NaN, because this shouldn't happen.



This method does not work and gives:
_/home/yunpeng/anaconda3/lib/python3.7/site-packages/galpy/actionAngle/actionAngleStaeckel.py:1077: RuntimeWarning: invalid value encountered in sqrt
  return numpy.sqrt(delta2)_

Not all of these  736 stars locate around z=0. For example one APOGEE star(2M03131971+7900477) gives a same error as above. 
```
o = Orbit(vxvv=[12.197* units.kpc, 104.0 * units.km / units.s, 219.1* units.km / units.s, 1.691 * units.kpc, -20.8 * units.km / units.s],ro=8.21,vo=233.1) 
```
By the way, these 736 stars seems symmetrically locate on each side of z=0. 
Thank you for your reply and have a nice day!

**Comment by jobovy** [comment]
@ yunpeng-jia: this is now fixed in the `main` branch (you can try it at the [REPL](https://www.galpy.org/repl)). Note that for this last orbit, ``estimateDeltaStaeckel`` now returns zero, because it's in a part of the potential where the potential is effectively spherical and delta=0 for a spherical potential. However, you can't actually run `actionAngleStaeckel` with `delta=0`, so if you do that, just give it a small value (``delta=1e-6`` or so). If you compute actions through the `Orbit` interface, this is handled automatically, so
```
o.jr(pot=McMillan17)
```
should just work now.

**Comment by yunpeng-jia** [comment]
> @yunpeng-jia: this is now fixed in the `main` branch (you can try it at the [REPL](https://www.galpy.org/repl)). Note that for this last orbit, `estimateDeltaStaeckel` now returns zero, because it's in a part of the potential where the potential is effectively spherical and delta=0 for a spherical potential. However, you can't actually run `actionAngleStaeckel` with `delta=0`, so if you do that, just give it a small value (`delta=1e-6` or so). If you compute actions through the `Orbit` interface, this is handled automatically, so
> 
> ```
> o.jr(pot=McMillan17)
> ```
> 
> should just work now.

Thank you.  Appreciate your help.

**Comment by jobovy** [comment]
> Thank you. Appreciate your help.

You're welcome! I've actually changed the code further to not return `delta=0`, but instead return `delta=1e-6`, because then you can just give it to `actionAngleStaeckel` without issues. Anyway, using the `Orbit` interface is still recommended.
