### ISSUE TITLE
Attempting to use other unit systems with galpy breaks silently

### ISSUE THREAD

**Issue by JBorrow** [jobovy/galpy#542]
## 🐛 Bug

Galpy fails silently when accidentally provided data with symbolic units produced by other packages (notably yt). It produces erroneous scientific results without even raising a warning.

### Reproducible example

Consider this setup:
```python
from galpy.util import conversion
import astropy.units as as_u
import unyt as yt_u

ro = 1 * as_u.kpc
vo = 1 * as_u.km / as_u.s

for mass in [1e8, 1e9, 1e10, 1e11, 1e12, 1e13, 1e14]:
    astropy_mass = conversion.parse_mass(mass * as_u.Msun, ro, vo)
    unyt_mass = conversion.parse_mass(mass * yt_u.Msun, ro, vo)

    print(f"Astropy: {astropy_mass}, unyt: {unyt_mass}")
```

This is a case of bad user behaviour - mixing unit systems - but can occur silently in the background. Even printing the arrays is not useful as no typing is included. The results of this mini script are:

```
Astropy: 430.09172700362797 s2 / (km2 kpc), unyt: 1.98841586e+38 kg
Astropy: 4300.917270036281 s2 / (km2 kpc), unyt: 1.98841586e+39 kg
Astropy: 43009.172700362804 s2 / (km2 kpc), unyt: 1.98841586e+40 kg
Astropy: 430091.727003628 s2 / (km2 kpc), unyt: 1.9884158600000002e+41 kg
Astropy: 4300917.27003628 s2 / (km2 kpc), unyt: 1.98841586e+42 kg
Astropy: 43009172.7003628 s2 / (km2 kpc), unyt: 1.9884158600000001e+43 kg
Astropy: 430091727.00362796 s2 / (km2 kpc), unyt: 1.98841586e+44 kg
```

So the numbers seem vaguely correct. However when trying to run a realistic example, in this case integrating galaxy orbits with dynamical friction, using units through astropy for the masses, or through unyt, give wildly different answers (with the latter obviously incorrect).

Astropy units:
<img width="394" alt="Screenshot 2023-01-20 at 11 56 41 AM" src="https://user-images.githubusercontent.com/7839515/213757637-fa4c365e-8261-4a1a-b916-05fab2247413.png">

Unyt units:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/7839515/213757767-2732dedb-1203-4335-aad4-d9a66cacd472.png">

### Expected behavior

Either galpy should handle other unit systems, or should raise an error. It should not proceed regardless. I had a look at the function `parse_mass` that appears to be the problem here, and I think it originates here:

`if _APY_LOADED and isinstance(x,units.Quantity) else x`

Nothing is done with the units unless we explicitly have an astropy units quantity, irrespective of the type passed. I would suggest instead maybe falling back to returning the regular value in known cases, e.g. a float, integer, or a numpy array, and allowing exceptions to be raised naturally by astropy if we think it has units but is behaving badly.

### System Details

```
>>> import platform; print(platform.platform())
macOS-13.1-arm64-arm-64bit
>>> import sys; print("Python", sys.version)
Python 3.9.7 (default, Aug 31 2021, 21:51:10)
[Clang 12.0.5 (clang-1205.0.22.9)]
>>> import numpy; print("numpy", numpy.__version__)
numpy 1.23.5
>>> import scipy; print("scipy", scipy.__version__)
scipy 1.9.3
>>> import matplotlib; print("matplotlib", matplotlib.__version__)
matplotlib 3.6.2
>>> import galpy; print("galpy", galpy.__version__)
galpy 1.8.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.2.1
```

### Additional context

Thanks to @taliaoshea for the initial investigation into this issue.

**Comment by jobovy** [comment]
Thanks for reporting this, I agree that this is bad behavior!

I think the best way to handle this is probably a decorator to check the inputs to the `parse_` functions; `ro` and `vo` are also supposed to be floats, not Quantities, although that's a minor issue here. I just hope that doesn't slow things down too much. 

In principle, it should be relatively easy to add support for using ``yt` units (or, say, `pint`), is this something that you think would be useful? Either way, it's important to make sure the input units are correctly parsed.

**Comment by JBorrow** [comment]
I think it totally makes sense to restrict things to just astropy units, as these libraries provide easy (but non-standard) conversion APIs, for us this was just a case of sticking in a few `.to_astropy()`s. But it took us a couple of months to figure out what the issue actually was, as none of our results made sense!

Re: ro, vo. If they are supposed to be floats, I think it makes sense to sanitize them too. The decorator could be optional in doing the checking? I.e. you could define it one way for 'fast mode' and not do any sanitization, and have strong checking for 'debug' mode by default?
