### ISSUE TITLE
list of array without astropy unit as vxvv to Orbit have no useful error msg

### ISSUE THREAD

**Issue by henrysky** [jobovy/galpy#548]
### Reproducible example

For example, if one want to set up galpy orbit from a data file where ra, dec, pmra... array are being read into separate arrays. A quick way to setup galpy orbit is 

```python
import numpy as np
from galpy.orbit import Orbit

o = Orbit(
    vxvv=[
        np.array([1, 2, 3]),
        np.array([1, 2, 3]),
        np.array([1, 2, 3]),
        np.array([1, 2, 3]),
        np.array([1, 2, 3]),
        np.array([1, 2, 3]),
    ],
    radec=True,
)
```

but this will raise the following error which is unclear what is wrong

```
File c:\users\henry\documents\github\galpy\galpy\orbit\Orbits.py:229, in Orbit.__init__(self, vxvv, ro, vo, zo, solarmotion, radec, uvw, lb)
    227     radec= True
    228 elif isinstance(vxvv,(list, tuple)):
--> 229     if None in vxvv:
    230         vxvv= [[0.,0.,0.,0.,0.,0.]
    231                if tvxvv is None else tvxvv
    232                for tvxvv in vxvv]
    233         radec= True
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

But if I do list of array with astropy unit instead of just a simple list of array, galpy will handle the `vxvv` without error
```python
import numpy as np
import astropy.units as u
from galpy.orbit import Orbit

o = Orbit(
    vxvv=[
        np.array([1, 2, 3]) * u.deg,
        np.array([1, 2, 3]) * u.deg,
        np.array([1, 2, 3]) * u.kpc,
        np.array([1, 2, 3]) * u.mas / u.yr,
        np.array([1, 2, 3]) * u.mas / u.yr,
        np.array([1, 2, 3]) * u.km / u.s,
    ],
    radec=True,
)
```

### Expected behavior

A simple list of array should be okay for `vxvv` or if by design users need to give a list of array with astropy unit as `vxvv`, galpy should raise a useful error message to user

### System Details
```
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC v.1929 64 bit (AMD64)]
numpy 1.24.1
scipy 1.9.3
matplotlib 3.6.2
galpy 1.8.2.dev0
astropy 5.2
```

**Comment by jobovy** [comment]
I agree that the error message is not very informative, but the first input is not supported according to the documentation, while the second one is, so the behavior is consistent with the documentation: https://docs.galpy.org/en/latest/reference/orbitinit.html

Maybe the easiest way to deal with this is just to support method 1, which shouldn't be that hard.

**Comment by jobovy** [comment]
I think this should now be fixed in `main`.
