### ISSUE TITLE
negative mass returned from galpy.potential.mass

### ISSUE THREAD

**Issue by sferrone** [jobovy/galpy#555]
## 🐛 Bug

Hello, I've found that one of the convenience functions for finding the enclosed mass returns a negative mass if we have negative values of z.

### Reproducible example

from galpy.potential import MWPotential2014 as MW14
from galpy.potential import mass
R=1.6303380979868902
z=1.2732319411637634
print(mass(MW14,R,z),mass(MW14,R,-z))
>> 1.3924105988548559 -1.3924105988548559

### Expected behavior
>> 1.3924105988548559 1.3924105988548559

### System Details

Linux-5.15.0-67-generic-x86_64-with-glibc2.35
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
numpy 1.21.5
scipy 1.8.0
matplotlib 3.5.1
galpy 1.8.1
astropy 5.0.2

**Comment by jobovy** [comment]
Thanks for the clear bug report! Should be an easy fix.
