### ISSUE TITLE
Cannot access galpy.util.coords

### ISSUE THREAD

**Issue by luismi98** [jobovy/galpy#590]
### Discussed in https://github.com/jobovy/galpy/discussions/589

<div type='discussions-op-text'>

<sup>Originally posted by **luismi98** July  2, 2023</sup>
Coords doesn´t seem to be located under galpy.util anymore. Below I show you how after a fresh pip install I can´t find it:

(base) PS C:\Users\Luismi> pip uninstall galpy

> Found existing installation: galpy 1.8.3
> Uninstalling galpy-1.8.3:
>   Would remove:
>     c:\users\luismi\anaconda3\lib\site-packages\galpy-1.8.3.dist-info\*
>     c:\users\luismi\anaconda3\lib\site-packages\galpy\*
>     c:\users\luismi\anaconda3\lib\site-packages\libgalpy.cp38-win_amd64.pyd
> Proceed (Y/n)? Y
>   Successfully uninstalled galpy-1.8.3

(base) PS C:\Users\Luismi> pip install galpy

> Collecting galpy
>   Using cached galpy-1.8.3-cp38-cp38-win_amd64.whl (783 kB)
> Requirement already satisfied: packaging in c:\users\luismi\appdata\roaming\python\python38\site-packages (from galpy) (21.3)
> Requirement already satisfied: numpy>=1.7 in c:\users\luismi\appdata\roaming\python\python38\site-packages (from galpy) (1.22.2)
> Requirement already satisfied: scipy in c:\users\luismi\anaconda3\lib\site-packages (from galpy) (1.5.2)
> Requirement already satisfied: matplotlib in c:\users\luismi\anaconda3\lib\site-packages (from galpy) (3.4.3)
> Requirement already satisfied: cycler>=0.10 in c:\users\luismi\anaconda3\lib\site-packages (from matplotlib->galpy) (0.10.0)
> Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\luismi\anaconda3\lib\site-packages (from matplotlib->galpy) (1.3.0)
> Requirement already satisfied: pillow>=6.2.0 in c:\users\luismi\appdata\roaming\python\python38\site-packages (from matplotlib->galpy) (9.0.1)
> Requirement already satisfied: pyparsing>=2.2.1 in c:\users\luismi\anaconda3\lib\site-packages (from matplotlib->galpy) (2.4.7)
> Requirement already satisfied: python-dateutil>=2.7 in c:\users\luismi\anaconda3\lib\site-packages (from matplotlib->galpy) (2.8.1)
> Requirement already satisfied: six in c:\users\luismi\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->galpy) (1.15.0)
> Installing collected packages: galpy
> Successfully installed galpy-1.8.3

(base) PS C:\Users\Luismi> python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

> import galpy as gal
> gal.
> 
> > gal.Version(               
> gal.configfilename         
> gal.http                   
> gal.parse_version(         
> gal.print_version_warning( gal.sys                    
> gal.write_config(
> gal.check_pypi_version(    
> gal.datetime               
> gal.latest_pypi_version(   
> gal.platform               
> gal.subprocess             
> gal.util
> 
> gal.util.
> 
> > gal.util.config               
> gal.util.galpyWarning(         
> gal.util.linalg                
> gal.util.numpy                 
> gal.util.pickle                
> gal.util.shutil                
> gal.util.tempfile
> gal.util.fast_cholesky_invert( 
> gal.util.galpyWarningVerbose(  
> gal.util.logsumexp(            
> gal.util.os                    
> gal.util.save_pickles(         
> gal.util.stable_cho_factor(    
> gal.util.warnings
> 
> gal.util.coords
> 
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> > AttributeError: module 'galpy.util' has no attribute 'coords'                                        </div>

**Comment by jobovy** [comment]
Hard to tell exactly what you are doing in your example, but I think you have to import it
```python
import galpy.util.coords
```
